name: SAT Test Dates Monitor

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Download the previous state file if it exists
      - name: Download previous state
        uses: actions/download-artifact@v3
        with:
          name: sat-monitor-state
          path: .
        continue-on-error: true

      - name: Run SAT Monitor
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "-1002594329611"
        run: |
          python sat_monitor.py

      # Upload the state file as an artifact for the next run
      - name: Upload state artifact
        uses: actions/upload-artifact@v3
        with:
          name: sat-monitor-state
          path: sat_monitor_state.json
          retention-days: 1