name: SAT Test Dates Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      # Download the previous state artifact
      - name: Download previous state
        id: download-state
        uses: actions/download-artifact@v4
        with:
          name: sat-monitor-state
          path: .
          # The following makes the step not fail if the artifact doesn't exist
          if-no-artifact-found: ignore

      # Initialize state if artifact wasn't found
      - name: Initialize state file if not found
        run: |
          if [ ! -f "sat_monitor_state.json" ]; then
            echo '{"timestamp": "", "last_modified": "", "test_date_count": 0, "test_dates": []}' > sat_monitor_state.json
            echo "Initialized empty sat_monitor_state.json as no previous state was found."
          else
            echo "Found existing state file from artifact:"
            cat sat_monitor_state.json
          fi
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run SAT Monitor
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID || '-1002594329611' }}
        run: |
          python sat_monitor.py

      - name: DEBUG - Check state file after script run
        run: |
          echo "--- DEBUG: State File After Script Run ---"
          cat sat_monitor_state.json
        shell: bash

      # Upload the updated state as an artifact
      - name: Upload state artifact
        uses: actions/upload-artifact@v4
        with:
          name: sat-monitor-state
          path: sat_monitor_state.json
          retention-days: 30
          overwrite: true

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sat-monitor-logs-${{ github.run_id }}
          path: sat_monitor.log
          retention-days: 5